//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp21
{
    using System;
    using System.Data.Entity;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Telefon { get; set; }
        public string Eposta { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> TownId { get; set; }
        public string Detail { get; set; }
    
        public virtual City City { get; set; }
        public virtual Town Town { get; set; }
    }
}
